- name: kubeadm | Reset if requested
  command: kubeadm reset
  when: reset
  tags:
    - reset

- name: kubeadm | Check for a running cluster
  command: kubectl get nodes
  become_user: pi
  register: kubectl_result
  failed_when: kubectl_result.rc == 2
  changed_when: kubectl_result.rc == 1

- block:

  - name: kubeadm | Setup master
    import_tasks: master.yml
    when: mode == "master"

  - name: kubeadm | Setup node
    import_tasks: node.yml
    when: mode == "slaves"

  when: kubectl_result.rc == 1 or reset