---
- name: Add and update packages
  import_tasks: apt.yml

- name: Fix iptable rules
  import_tasks: iptables.yml

- name: Create dir ~/.kube
  file: path=/home/pi/.kube state=directory owner=pi group=users mode=0775

- name: Create dir /etc/kubernetes/apps
  file: path=/etc/kubernetes/apps state=directory mode=0775

- name: Setup profile
  template: src=kubernetes_profile.sh dest=/etc/profile.d/kubernetes.sh mode=0644

- name: Install with kubeadm
  import_tasks: kubeadm.yml