---
- name: Kubernetes Master

  hosts: master
  remote_user: pi
  become: true

  roles:
  - role: kubernetes-full-reset
    mode: master

- name: Kubernetes Nodes

  hosts: slaves
  remote_user: pi
  become: true

  roles:
  - role: kubernetes-full-reset
    mode: slaves