# Especially saving of the iptables rules needs to be fixed

- name: flannel | Create flannel resources
  template: src=cni/flannel.yml dest=/etc/kubernetes/kube-flannel.yml

- name: flannel | Create flannel resources
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf